GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoibW9tb2EzQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Im1vbW9hMyIsImlhdCI6MTY3NjcwNjA5NiwiZXhwIjoxNjc2NzA2Njk2fQ.nubGAvHBlfqtpa6Tj1JL9ZQ7uyROmBby3m6QzXvAZtg

###
POST http://localhost:5000/api/users
Content-Type:application/json

{ 
    "user_email":"momoa3@gmail.com",
    "user_name":"momoa3",
    "user_pw":"12345",
    "confPassword":"12345"

}

//로그인
###
POST http://localhost:5000/api/signin
Content-Type:application/json

{ 
    "user_email":"momoa3@gmail.com",
    "user_pw":"12345"
}

//리프레쉬토큰 ->액세스토큰갱신
###
GET http://localhost:5000/api/token

###
DELETE http://localhost:5000/api/logout