GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoiYWhmbDExMjlAaGFubWFpbC5uZXQiLCJ1c2VyX25hbWUiOiLrh6zsiJgiLCJpYXQiOjE2NzcxMzExMjQsImV4cCI6MTY3NzEzMTE0NH0.q6gKS4IrhbMiIuwoIESMQIZEXF6LJXkYjFlSQGaizKM
###
POST http://localhost:5000/api/users
Content-Type:application/json

{ 
    "user_email":"momoa3@gmail.com",
    "user_name":"momoa3",
    "user_pw":"12345",
    "confPassword":"12345"

}

//로그인
###
POST http://localhost:5000/api/signin
Content-Type:application/json

{ 

    "user_email":"momoa4@gmail.com",
    "user_pw":"12345qwert"

}

//리프레쉬토큰 ->액세스토큰갱신
###
GET http://localhost:5000/api/token

###
DELETE http://localhost:5000/api/logout


//카카오로그인
###
POST http://localhost:5000/api/getkakao
Content-Type:application/json

{ 
    "user_email":"laura1129@naver.com"
    
}



//getsheetid불러오기
###
GET http://localhost:5000/api/getsheetid
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoibW9tb2E0QGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6ImttaiIsImlhdCI6MTY3NzE1NTMxMywiZXhwIjoxNjc3MTU2NTEzfQ.hgEVl_7-3fgAYzr16em7gRzB2A6b4JhhlPy9cT_NiCc

//개인정보불러오기
###
GET http://localhost:5000/api/getpersonalinfo
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoibW9tb2E0QGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6ImttaiIsImlhdCI6MTY3NzE1NTQ5MiwiZXhwIjoxNjc3MTU2NjkyfQ.SxccFIzND6PgpvY_0xo6wQbk75HZAvtmanyqor2Qwls

